title    KinetixOS live (CachyOS BORE, NVIDIA open, UEFI)
sort-key 03
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-cachyos-bore-nvidia-open
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-cachyos-bore-nvidia-open.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID%
